apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workguide.fullname" . }}-config
  namespace: {{ include "workguide.namespace" . }}
  labels:
    {{- include "workguide.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | default "" | indent 4 }}
